# Generated by Django 4.0.4 on 2022-05-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
