# Generated by Django 4.0.4 on 2022-05-14 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conditions', '0001_initial'),
        ('patients', '0006_alter_patient_address'),
        ('providers', '0002_rename_providers_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('authorised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.provider')),
                ('dieses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conditions.condition')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
            ],
        ),
    ]
