# Generated by Django 4.0.4 on 2022-05-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness', models.CharField(max_length=200)),
                ('treatment', models.TextField()),
                ('diagnosed', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
